apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-deployment
  template:
    metadata:
      labels:
        app: web-deployment
    spec:
      containers:
        - name: web
          image: web:1.0 # Replace this with the actual name of your image
          ports:
            - containerPort: {{ .Values.service.port }}