apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "languages-ai.fullname" . }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ include "languages-ai.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "languages-ai.fullname" . }}
    spec:
      containers:
        - name: web
          image: web:1.0 # Replace this with the actual name of your image
          ports:
            - containerPort: {{ .Values.service.port }}