apiVersion: v1
kind: Service
metadata:
  name: {{ include "languages-ai.fullname" . }}
spec:
  selector:
    app: web
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3000
  type: LoadBalancer