apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: user-auth-service
spec:
  selector:
    app: user-auth
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: user-auth-db-service
spec:
  selector:
    app: user-auth-db-service
  ports:
    - name: user-auth-db-service
      port: 5432
      targetPort: 5432